const http=require('node:http');const dgram=require('node:dgram');const os=require('node:os');
const DISCOVERY_PORT=45820,BATTLE_PORT=45821;let server=null,broadcaster=null,profile=null;
const addresses=()=>Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>x.address);
function resolveBattle(defender,challenger){const attack=Math.max(5,Math.round((challenger.move?.power||40)*(challenger.level||1)/12));const counter=Math.max(5,Math.round(40*(defender.level||1)/12));const won=attack>=counter,stones=['Fire Stone','Moon Stone','Thunder Stone','Shiny Stone'];return{won,attack,counter,opponent:defender,exp:won?100+(defender.level||1)*12:35,item:won?stones[(defender.level||1)%stones.length]:null}}
function startHost(nextProfile){profile=nextProfile;if(server)return{port:BATTLE_PORT,addresses:addresses()};server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET'&&req.url==='/status')return res.end(JSON.stringify({profile}));if(req.method==='POST'&&req.url==='/battle'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{res.end(JSON.stringify(resolveBattle(profile,JSON.parse(body))))}catch{res.statusCode=400;res.end(JSON.stringify({error:'Invalid battle request'}));}});return}res.statusCode=404;res.end('{}')});server.listen(BATTLE_PORT,'0.0.0.0');broadcaster=dgram.createSocket('udp4');broadcaster.bind(()=>{broadcaster.setBroadcast(true);const announce=()=>{const data=Buffer.from(JSON.stringify({kind:'poketamagachi',port:BATTLE_PORT,name:profile?.name||'Trainer',species:profile?.species||'Pokémon',level:profile?.level||1}));broadcaster.send(data,DISCOVERY_PORT,'255.255.255.255')};announce();broadcaster._timer=setInterval(announce,2000)});return{port:BATTLE_PORT,addresses:addresses()}}
function discover(timeout=2500){return new Promise(resolve=>{const found=new Map(),sock=dgram.createSocket({type:'udp4',reuseAddr:true});sock.on('message',(msg,rinfo)=>{try{const data=JSON.parse(msg);if(data.kind==='poketamagachi')found.set(rinfo.address,{...data,address:rinfo.address})}catch{}});sock.bind(DISCOVERY_PORT);setTimeout(()=>{sock.close();resolve([...found.values()])},timeout)})}
function challenge(peer,payload){return new Promise((resolve,reject)=>{const body=JSON.stringify(payload),req=http.request({host:peer.address,port:peer.port||BATTLE_PORT,path:'/battle',method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)},timeout:5000},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{resolve(JSON.parse(out))}catch{reject(new Error('Invalid response'))}})});req.on('error',reject);req.on('timeout',()=>req.destroy(new Error('Battle timed out')));req.end(body)})}
function stop(){if(server)server.close();if(broadcaster){clearInterval(broadcaster._timer);broadcaster.close()}server=null;broadcaster=null}
module.exports={startHost,discover,challenge,stop,resolveBattle};
