const http=require('node:http');const dgram=require('node:dgram');const os=require('node:os');
const DISCOVERY_PORT=45820,BATTLE_PORT=45821;let server=null,broadcaster=null,profile=null,members=[];
const addresses=()=>Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>x.address);
function resolveBattle(defender,challenger){const attack=Math.max(5,Math.round((challenger.move?.power||40)*(challenger.level||1)/12)),counter=Math.max(5,Math.round(40*(defender.level||1)/12)),challengerFirst=(challenger.speed||0)>=(defender.speed||0),order=challengerFirst?['challenger','defender']:['defender','challenger'],hp={challenger:100,defender:100},turns=[];let round=1;while(hp.challenger>0&&hp.defender>0&&round<=50){for(const actor of order){if(hp.challenger<=0||hp.defender<=0)break;const target=actor==='challenger'?'defender':'challenger',damage=actor==='challenger'?attack:counter,name=actor==='challenger'?(challenger.species||challenger.name):(defender.species||defender.name),move=actor==='challenger'?(challenger.move?.name||'Attack'):'Attack';hp[target]=Math.max(0,hp[target]-damage);turns.push({round,actor,target,damage,remainingHp:hp[target],text:`Turn ${round} · ${name} used ${move}!${hp[target]===0?' It is unable to battle!':''}`})}round++}const won=hp.defender===0,stones=['Fire Stone','Moon Stone','Thunder Stone','Shiny Stone'];return{won,attack,counter,first:challengerFirst?'challenger':'defender',turns,finalHp:hp,opponent:defender,exp:won?100+(defender.level||1)*12:35,item:won?stones[(defender.level||1)%stones.length]:null}}
function readBody(req,done){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{done(null,JSON.parse(body||'{}'))}catch(error){done(error)}})}
function startHost(nextProfile){profile=nextProfile;if(server)return{port:BATTLE_PORT,addresses:addresses(),profile,members};members=[];server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET'&&req.url==='/status')return res.end(JSON.stringify({profile,members}));if(req.method==='POST'&&req.url==='/join')return readBody(req,(error,guest)=>{if(error){res.statusCode=400;return res.end(JSON.stringify({error:'Invalid room request'}))}if(guest.id&&guest.id===profile?.id){res.statusCode=409;return res.end(JSON.stringify({error:'You cannot join your own room.'}))}const member={...guest,address:req.socket.remoteAddress?.replace('::ffff:',''),port:guest.port||BATTLE_PORT};members=members.filter(x=>x.id!==member.id);members.push(member);res.end(JSON.stringify({profile,members}))});if(req.method==='POST'&&req.url==='/battle')return readBody(req,(error,challenger)=>{if(error){res.statusCode=400;return res.end(JSON.stringify({error:'Invalid battle request'}))}res.end(JSON.stringify(resolveBattle(profile,challenger)))});res.statusCode=404;res.end('{}')});server.listen(BATTLE_PORT,'0.0.0.0');broadcaster=dgram.createSocket('udp4');broadcaster.bind(()=>{broadcaster.setBroadcast(true);const announce=()=>{const data=Buffer.from(JSON.stringify({kind:'poketamagachi',id:profile?.id,port:BATTLE_PORT,name:profile?.name||'Trainer',species:profile?.species||'Pokémon',level:profile?.level||1}));broadcaster.send(data,DISCOVERY_PORT,'255.255.255.255')};announce();broadcaster._timer=setInterval(announce,2000)});return{port:BATTLE_PORT,addresses:addresses(),profile,members}}
function discover(timeout=2500){return new Promise(resolve=>{const found=new Map(),sock=dgram.createSocket({type:'udp4',reuseAddr:true});sock.on('message',(msg,rinfo)=>{try{const data=JSON.parse(msg);if(data.kind==='poketamagachi')found.set(rinfo.address,{...data,address:rinfo.address})}catch{}});sock.bind(DISCOVERY_PORT);setTimeout(()=>{sock.close();resolve([...found.values()])},timeout)})}
function request(peer,path,method='GET',payload){return new Promise((resolve,reject)=>{const body=payload?JSON.stringify(payload):'',req=http.request({host:peer.address,port:peer.port||BATTLE_PORT,path,method,headers:body?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}:{},timeout:5000},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{const data=JSON.parse(out);if(res.statusCode>=400)return reject(new Error(data.error||'Room request failed'));resolve(data)}catch{reject(new Error('Invalid room response'))}})});req.on('error',reject);req.on('timeout',()=>req.destroy(new Error('Room request timed out')));req.end(body)})}
const joinRoom=(peer,guest)=>request(peer,'/join','POST',guest);const roomStatus=peer=>request(peer,'/status');const challenge=(peer,payload)=>request(peer,'/battle','POST',payload);
function stop(){if(server)server.close();if(broadcaster){clearInterval(broadcaster._timer);broadcaster.close()}server=null;broadcaster=null;members=[]}
module.exports={startHost,discover,joinRoom,roomStatus,challenge,stop,resolveBattle};
