const http=require('node:http');const dgram=require('node:dgram');const os=require('node:os');
const DISCOVERY_PORT=45820,BATTLE_PORT=45821;let server=null,broadcaster=null,profile=null,members=[];
const addresses=()=>Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>x.address);
const matchups={normal:{half:['rock','steel'],none:['ghost']},fire:{double:['grass','ice','bug','steel'],half:['fire','water','rock','dragon']},water:{double:['fire','ground','rock'],half:['water','grass','dragon']},electric:{double:['water','flying'],half:['electric','grass','dragon'],none:['ground']},grass:{double:['water','ground','rock'],half:['fire','grass','poison','flying','bug','dragon','steel']},ice:{double:['grass','ground','flying','dragon'],half:['fire','water','ice','steel']},fighting:{double:['normal','ice','rock','dark','steel'],half:['poison','flying','psychic','bug','fairy'],none:['ghost']},poison:{double:['grass','fairy'],half:['poison','ground','rock','ghost'],none:['steel']},ground:{double:['fire','electric','poison','rock','steel'],half:['grass','bug'],none:['flying']},flying:{double:['grass','fighting','bug'],half:['electric','rock','steel']},psychic:{double:['fighting','poison'],half:['psychic','steel'],none:['dark']},bug:{double:['grass','psychic','dark'],half:['fire','fighting','poison','flying','ghost','steel','fairy']},rock:{double:['fire','ice','flying','bug'],half:['fighting','ground','steel']},ghost:{double:['psychic','ghost'],half:['dark'],none:['normal']},dragon:{double:['dragon'],half:['steel'],none:['fairy']},dark:{double:['psychic','ghost'],half:['fighting','dark','fairy']},steel:{double:['ice','rock','fairy'],half:['fire','water','electric','steel']},fairy:{double:['fighting','dragon','dark'],half:['fire','poison','steel']}};
function effectiveness(type,targetTypes=[]){const chart=matchups[type]||{},targets=targetTypes||[];return targets.reduce((value,target)=>value*(chart.none?.includes(target)?0:chart.double?.includes(target)?2:chart.half?.includes(target)?0.5:1),1)}
function critChance(stage=0){return[1/16,1/8,1/4,1/3,1/2][Math.min(4,Math.max(0,stage))]}
function damageFor(attacker,defender,move,rng=Math.random){if(!move?.power)return{damage:0,effectiveness:1,critical:false};const multiplier=effectiveness(move.type,defender.types),stab=attacker.types?.includes(move.type)?1.5:1,critical=rng()<critChance(move.critRate||0),base=Math.max(1,Math.round(move.power*(attacker.level||1)/12));return{damage:multiplier===0?0:Math.max(1,Math.round(base*stab*multiplier*(critical?1.5:1))),effectiveness:multiplier,critical}}
function resultText(name,move,outcome,knockedOut){const effect=outcome.effectiveness===0?' It had no effect.':outcome.effectiveness>1?' It was super effective!':outcome.effectiveness<1?' It was not very effective.':'';const critical=outcome.critical?' A critical hit!':'';const status=!move.power?' It dealt no direct damage.':'';return`${name} used ${move.name||'Attack'}!${critical}${effect}${status}${knockedOut?' It is unable to battle!':''}`}
function resolveBattle(defender,challenger,rng=Math.random){const initialHp={challenger:challenger.battleState?.challengerHp??100,defender:challenger.battleState?.defenderHp??100},hp={...initialHp},round=challenger.battleState?.round||1,enemyMoves=(defender.moveSet||[]).filter(move=>move?.power>0),enemyMove=enemyMoves[(round-1)%Math.max(1,enemyMoves.length)]||{name:'Struggle',type:'normal',power:50,priority:0},playerOutcome=damageFor(challenger,defender,challenger.move,rng),enemyOutcome=damageFor(defender,challenger,enemyMove,rng),playerPriority=challenger.move?.priority||0,enemyPriority=enemyMove.priority||0,challengerFirst=playerPriority!==enemyPriority?playerPriority>enemyPriority:(challenger.speed||0)>=(defender.speed||0),order=challengerFirst?['challenger','defender']:['defender','challenger'],turns=[];for(const actor of order){if(hp.challenger<=0||hp.defender<=0)break;const target=actor==='challenger'?'defender':'challenger',outcome=actor==='challenger'?playerOutcome:enemyOutcome,name=actor==='challenger'?(challenger.species||challenger.name):(defender.species||defender.name),move=actor==='challenger'?challenger.move:enemyMove;hp[target]=Math.max(0,hp[target]-outcome.damage);turns.push({round,actor,target,...outcome,remainingHp:hp[target],text:resultText(name,move,outcome,hp[target]===0)})}const finished=hp.challenger===0||hp.defender===0,won=finished&&hp.defender===0,stones=['Fire Stone','Moon Stone','Thunder Stone','Shiny Stone'];return{won,finished,round,attack:playerOutcome.damage,counter:enemyOutcome.damage,priority:{challenger:playerPriority,defender:enemyPriority},first:challengerFirst?'challenger':'defender',turns,initialHp,finalHp:hp,opponent:defender,exp:finished?(won?100+(defender.level||1)*12:35):0,item:finished&&won?stones[(defender.level||1)%stones.length]:null}}
function readBody(req,done){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{done(null,JSON.parse(body||'{}'))}catch(error){done(error)}})}
function startHost(nextProfile){profile=nextProfile;if(server)return{port:BATTLE_PORT,addresses:addresses(),profile,members};members=[];server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET'&&req.url==='/status')return res.end(JSON.stringify({profile,members}));if(req.method==='POST'&&req.url==='/join')return readBody(req,(error,guest)=>{if(error){res.statusCode=400;return res.end(JSON.stringify({error:'Invalid room request'}))}if(guest.id&&guest.id===profile?.id){res.statusCode=409;return res.end(JSON.stringify({error:'You cannot join your own room.'}))}const member={...guest,address:req.socket.remoteAddress?.replace('::ffff:',''),port:guest.port||BATTLE_PORT};members=members.filter(x=>x.id!==member.id);members.push(member);res.end(JSON.stringify({profile,members}))});if(req.method==='POST'&&req.url==='/battle')return readBody(req,(error,challenger)=>{if(error){res.statusCode=400;return res.end(JSON.stringify({error:'Invalid battle request'}))}res.end(JSON.stringify(resolveBattle(profile,challenger)))});res.statusCode=404;res.end('{}')});server.listen(BATTLE_PORT,'0.0.0.0');broadcaster=dgram.createSocket('udp4');broadcaster.bind(()=>{broadcaster.setBroadcast(true);const announce=()=>{const data=Buffer.from(JSON.stringify({kind:'poketamagachi',id:profile?.id,port:BATTLE_PORT,name:profile?.name||'Trainer',species:profile?.species||'Pokémon',level:profile?.level||1}));broadcaster.send(data,DISCOVERY_PORT,'255.255.255.255')};announce();broadcaster._timer=setInterval(announce,2000)});return{port:BATTLE_PORT,addresses:addresses(),profile,members}}
function discover(timeout=2500){return new Promise(resolve=>{const found=new Map(),sock=dgram.createSocket({type:'udp4',reuseAddr:true});sock.on('message',(msg,rinfo)=>{try{const data=JSON.parse(msg);if(data.kind==='poketamagachi')found.set(rinfo.address,{...data,address:rinfo.address})}catch{}});sock.bind(DISCOVERY_PORT);setTimeout(()=>{sock.close();resolve([...found.values()])},timeout)})}
function request(peer,path,method='GET',payload){return new Promise((resolve,reject)=>{const body=payload?JSON.stringify(payload):'',req=http.request({host:peer.address,port:peer.port||BATTLE_PORT,path,method,headers:body?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}:{},timeout:5000},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{const data=JSON.parse(out);if(res.statusCode>=400)return reject(new Error(data.error||'Room request failed'));resolve(data)}catch{reject(new Error('Invalid room response'))}})});req.on('error',reject);req.on('timeout',()=>req.destroy(new Error('Room request timed out')));req.end(body)})}
const joinRoom=(peer,guest)=>request(peer,'/join','POST',guest);const roomStatus=peer=>request(peer,'/status');const challenge=(peer,payload)=>request(peer,'/battle','POST',payload);
function stop(){if(server)server.close();if(broadcaster){clearInterval(broadcaster._timer);broadcaster.close()}server=null;broadcaster=null;members=[]}
module.exports={startHost,discover,joinRoom,roomStatus,challenge,stop,resolveBattle,effectiveness,damageFor};
