const view=document.querySelector('#view');const KEY='poketamagachi.save.v1';let state=load();let query='';let type='all';let peers=[];let battleMessage='',roomRole='',roomPeer=null,roomData=null,battleTarget=null,battleResult=null,battleState=null,battlePending=false,battleStep=-1,battleReturnTimer=null;
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(!saved)return null;const entry=POKE_CATALOG.find(p=>p.id===saved.id);if(!entry){localStorage.removeItem(KEY);return null}saved.forms=entry.forms;saved.evolutionRules=entry.evolutionRules;saved.formIndex=saved.formIndex||0;if(typeof saved.isHatched!=='boolean'){saved.isHatched=true;saved.hatchedAt=saved.bornAt}saved.carePoints=saved.carePoints||0;saved.level=saved.level||1;saved.exp=saved.exp||0;saved.learnsets=BATTLE_DATA.learnsetsFor(entry.forms);saved.learnset=saved.learnsets[entry.forms[saved.formIndex]?.id]||BATTLE_DATA.learnsetFor(entry.type,entry.id);const earned=[...new Set(saved.learnset.filter(x=>x.level<=saved.level).map(x=>x.move))];saved.moves=saved.moves||earned.slice(-4);saved.moveArchive=[...new Set([...(saved.moveArchive||saved.moves),...earned])];saved.pendingMoves=saved.pendingMoves||[];const statNames=['hp','attack','defense','spAttack','spDefense','speed'];saved.ivs=saved.ivs||Object.fromEntries(statNames.map(s=>[s,0]));saved.evs=saved.evs||Object.fromEntries(statNames.map(s=>[s,0]));return PokeState.checkEvolution(saved)}catch{return null}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function petDef(){return POKE_CATALOG.find(p=>p.id===state?.id)}function img(p,cls=''){return `<img class="${cls}" src="${p.sprite}" onerror="if(this.src!=='${p.fallback}')this.src='${p.fallback}'" alt="${p.name} pixel sprite">`}
function currentForm(p){return p.forms?.[state?.formIndex||0]||p}
function petVisual(form){return state.isHatched?img(form,'pet-sprite evolution-pop'):`<div class="pixel-egg" role="img" aria-label="Mystery Pokémon egg"><i></i></div>`}
function careLabel(action){if(state.isHatched)return action;return{feed:'warm',play:'talk',rest:'rest',clean:'clean',heal:'check'}[action]}
function stat(k,v){return `<div class="stat"><span>${k.toUpperCase()} ${Math.round(v)}</span><div class="track"><div class="fill" style="width:${v}%"></div></div></div>`}
function needsPanel(s){const keys=state.isHatched?['hunger','happiness','energy','hygiene','health']:['happiness','hygiene','health'],cut=Math.ceil(keys.length/2),column=items=>`<div>${items.map(k=>stat(k,s[k])).join('')}</div>`;return `<div class="stats needs-columns">${column(keys.slice(0,cut))}${column(keys.slice(cut))}</div>`}
function expMeter(){const needed=PokeState.expForNext(state.level),percent=Math.min(100,Math.round((state.exp/needed)*100));return `<div class="exp-meter"><div><strong>LV.${state.level}</strong><span>EXP ${state.exp} / ${needed}</span></div><div class="exp-track" role="progressbar" aria-label="Experience toward level ${state.level+1}" aria-valuemin="0" aria-valuemax="${needed}" aria-valuenow="${state.exp}"><i style="width:${percent}%"></i></div></div>`}
function home(){if(!state)return `<section class="page starter-intro"><button class="giant-pokeball" data-nav="directory" aria-label="Choose your starter"><i></i></button><h1>Choose your starter</h1><button class="btn" data-nav="directory">View Pokémon</button></section>`;
  state=PokeState.advance(state);save();const p=petDef(),form=currentForm(p),s=state.stats;const eggText=`CARE ${Math.min(state.carePoints||0,3)}/3 · ${Date.now()-state.bornAt>=86400000?'READY TO HATCH':'KEEP CARING DAILY'}`,careActions=state.isHatched?['feed','play','rest','clean','heal']:['play','clean','heal'];return `<section class="page home-page"><div class="device"><div class="screen ${state.alive?'':'dead'}"><div class="screen-head"><span>${state.isHatched?form.name.toUpperCase():'MYSTERY EGG'}</span><span>${state.isHatched?(form.types||[p.type]).join(' / ').toUpperCase():'EGG'}</span></div>${expMeter()}<div class="pet-stage">${petVisual(form)}<div><div class="pet-name-row"><h2>${state.isHatched?form.name:'MYSTERY EGG'}</h2>${state.canEvolve?'<button class="evolve-btn" data-evolve>EVOLVE</button>':''}</div><p>${state.alive?(state.isHatched?mood(s):eggText):'Your companion has passed on.'}</p></div></div>${needsPanel(s)}</div><div class="actions ${state.isHatched?'':'egg-actions'}">${state.alive?careActions.map(a=>`<button class="action" data-action="${a}"><span>${careLabel(a)}</span></button>`).join(''):`<button class="action" data-restart><span>restart</span></button>`}</div></div><div class="feature-row"><button class="btn secondary" data-nav="journal">Journal</button><button class="btn" data-nav="hub">Battle / Train</button></div></section>`}
function mood(s){const low=Object.entries(s).filter(([,v])=>v<30).sort((a,b)=>a[1]-b[1])[0];if(!low)return 'Everything feels just right!';return {hunger:'My tummy is rumbling…',happiness:'Can we play for a while?',energy:'I need a little nap.',hygiene:'My habitat needs cleaning.',health:'I do not feel very well…'}[low[0]]}
function directory(){if(state?.alive)return home();const list=POKE_CATALOG.filter(p=>(type==='all'||p.type===type)&&p.name.toLowerCase().includes(query.toLowerCase()));const types=[...new Set(POKE_CATALOG.map(p=>p.type))];return `<section class="page"><div class="directory-head"><div><div class="eyebrow">Companion directory · ${POKE_CATALOG.length} available</div><h1>Choose your starter</h1></div><p>Every starter begins as an egg.</p></div><div class="filters"><input id="search" value="${query}" placeholder="Search by name…"><select id="type"><option value="all">All types</option>${types.map(t=>`<option ${t===type?'selected':''}>${t}</option>`).join('')}</select></div><div class="grid">${list.map(p=>`<article class="card" data-pokemon="${p.id}">${img(p)}<span class="type">#${String(p.id).padStart(3,'0')} · ${p.type}</span><h3>${p.name}</h3><button class="choose-card" type="button">Choose</button></article>`).join('')}</div></section>`}
function journal(){if(!state)return `<section class="page"><button class="ghost" data-nav="home">← Back</button><div class="empty"><h1>No memories yet.</h1><p>Choose a companion to begin your journal.</p><button class="btn" data-nav="directory">Browse directory</button></div></section>`;return `<section class="page"><button class="ghost" data-nav="home">← Habitat</button><div class="eyebrow">Shared memories</div><h1>Journal</h1><div class="journal">${state.journal.map(e=>`<div class="journal-item"><time>${new Date(e.at).toLocaleString()}</time><strong>${e.text}</strong></div>`).join('')}</div></section>`}
function about(){return `<section class="page"><div class="empty"><div class="eyebrow">Care guide</div><h1>A little care goes a long way.</h1><p>Needs decay based on real elapsed time—even when the app is closed. Feed, play, rest, clean, and heal your companion. Neglected critical needs lower health; zero health ends the lifecycle and unlocks a fresh start.</p><button class="btn" data-nav="directory">Meet the roster</button></div></section>`}
function moveName(id){return BATTLE_DATA.moves[id]?.name||id}function hub(){if(!state)return home();const waiting=state.isHatched?'Find players on this Wi‑Fi':'Opens after your egg hatches';return `<section class="page feature-page"><button class="ghost" data-nav="home">← Habitat</button><h1>Battle / Train</h1><div class="hub-grid"><button class="hub-card" data-nav="battle"><strong>Battle</strong><span>${waiting}</span></button><button class="hub-card" data-nav="train"><strong>Train</strong><span>Level, EXP, stats and moves</span></button></div></section>`}
function nextEvolution(){const rule=state.evolutionRules?.[state.formIndex];if(!rule)return'Final evolution';return rule.type==='level'?`Level ${rule.value}`:rule.type==='random'?`Random Eevee evolution at level ${rule.value}`:rule.type==='item'?`Use ${rule.value}`:rule.type==='trade'?'Trade with another player':rule.type==='friendship-day'?'High friendship during daytime':'High friendship'}
function duration(ms){const seconds=Math.max(0,Math.ceil(ms/1000)),h=String(Math.floor(seconds/3600)).padStart(1,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return`${h}:${m}:${s}`}
function daycarePanel(){const away=PokeState.isInDaycare(state),remaining=away?state.daycareUntil-Date.now():PokeState.DAYCARE_DURATION;return `<div class="daycare-card"><strong>DAYCARE TRAINING</strong><span>${away?'Your Pokémon is training. Returns in':'Two-hour solo EXP session'}</span><time id="daycare-timer">${duration(remaining)}</time><button class="btn" data-daycare ${away||!state.isHatched?'disabled':''}>${away?'AT DAYCARE':'SEND TO DAYCARE'}</button></div>`}
function train(){if(!state)return home();const available=state.moveArchive.filter(m=>!state.moves.includes(m)),labels={hp:'HP',attack:'ATK',defense:'DEF',spAttack:'SP.ATK',spDefense:'SP.DEF',speed:'SPEED'};return `<section class="page feature-page"><button class="ghost" data-nav="hub">← Battle / Train</button><h1>Train</h1>${expMeter()}${state.isHatched?`<div class="battle-message">NEXT: ${nextEvolution()}</div>`:'<div class="battle-message">Your Pokémon is still inside the egg. Care for it until it hatches; training and moves will then unlock.</div>'}${daycarePanel()}<h2>IVs / EVs</h2><div class="stat-grid">${Object.keys(labels).map(k=>`<div><span>${labels[k]}</span><strong>IV ${state.ivs[k]}</strong><strong>EV ${state.evs[k]}</strong></div>`).join('')}</div>${state.isHatched?`<h2>Moves (${state.moves.length}/4)</h2><div class="move-list">${state.moves.map(m=>`<div class="move-card"><strong>${moveName(m)}</strong><span>${BATTLE_DATA.moves[m]?.type||'normal'} · ${BATTLE_DATA.moves[m]?.power||'status'} power${BATTLE_DATA.moves[m]?.priority?` · priority +${BATTLE_DATA.moves[m].priority}`:''}</span></div>`).join('')}</div><h2>Move Relearner</h2>${available.length?available.map(m=>`<div class="move-card"><strong>${moveName(m)}</strong><div class="replace-row">${state.moves.map((x,i)=>`<button data-relearn="${m}" data-slot="${i}">Replace ${moveName(x)}</button>`).join('')}</div></div>`).join(''):'<p>No forgotten moves.</p>'}`:''}</section>`}
function battleProfile(){const form=currentForm(petDef());return{id:`${state.id}-${state.bornAt}`,name:state.name,species:form.name,types:form.types||[petDef().type],level:state.level,speed:state.level*2+(state.ivs?.speed||0)+Math.floor((state.evs?.speed||0)/4),moves:state.moves,moveSet:state.moves.map(id=>BATTLE_DATA.moves[id]),formId:form.id,sprite:form.sprite,fallback:form.fallback}}
function battleArena(peer){const mine=battleProfile(),result=battleResult,turns=result?.turns||[],shown=result?turns.slice(0,Math.min(turns.length,battleStep+1)):[],base=result?.initialHp||{challenger:battleState?.myHp??100,defender:battleState?.enemyHp??100},enemyDamage=shown.filter(t=>t.actor==='challenger').reduce((n,t)=>n+t.damage,0),myDamage=shown.filter(t=>t.actor==='defender').reduce((n,t)=>n+t.damage,0),enemyHp=Math.max(0,base.defender-enemyDamage),myHp=Math.max(0,base.challenger-myDamage),roundDone=result&&battleStep>=turns.length,message=battlePending?'Move selected…':!result?`What will ${mine.species} do?`:roundDone?(result.finished?`${result.won?'You won the battle!':'You lost the battle!'} +${result.exp} EXP · Returning to room…`:'Choose the next move…'):turns[battleStep]?.text;return `<div class="gen5-battle"><div class="wireless-strip"><button data-exit-battle>← ROOM</button><span>IR · ONLINE · WIRELESS</span><b>●●●</b></div><div class="battlefield"><div class="battle-hud enemy-hud"><strong>${peer.species}</strong><span>Lv.${peer.level}</span><div><i style="width:${enemyHp}%"></i></div><small>HP</small></div><div class="battle-hud player-hud"><strong>${mine.species}</strong><span>Lv.${mine.level}</span><div><i style="width:${myHp}%"></i></div><small>HP ${myHp} / 100</small></div><div class="combatant enemy"><img src="${peer.sprite||''}" onerror="this.src='${peer.fallback||''}'" alt="${peer.species}"></div><div class="combatant player"><img src="${mine.sprite}" onerror="this.src='${mine.fallback}'" alt="${mine.species}"></div></div><div class="battle-dialog">${message}</div><div class="gen5-moves">${state.moves.map(m=>{const move=BATTLE_DATA.moves[m]||{};return`<button data-battle-move="${m}" ${result||battlePending?'disabled':''}><strong>${moveName(m)}</strong><span>${(move.type||'normal').toUpperCase()} · PP ${move.pp||0}/${move.pp||0}${move.priority?` · PRI +${move.priority}`:''}</span></button>`}).join('')}</div></div>`}
function roomView(){const host=roomData?.profile,members=roomData?.members||[];if(battleTarget)return battleArena(battleTarget);return `<div class="room-panel"><div class="room-title"><strong>${roomRole==='host'?'Your Room':`${host?.name||'Trainer'}’s Room`}</strong><span>${roomRole==='host'?'Waiting for players on this Wi‑Fi':'Joined successfully'}</span></div><button class="btn secondary" data-refresh-room>Refresh Room</button><div class="move-list">${roomRole==='guest'&&host?`<div class="move-card"><strong>${host.name} · ${host.species} Lv.${host.level}</strong><button data-enter-battle="host">Enter Battle</button></div>`:''}${members.map((m,i)=>`<div class="move-card"><strong>${m.name} · ${m.species} Lv.${m.level}</strong>${roomRole==='host'?`<button data-enter-battle="${i}">Enter Battle</button>`:''}</div>`).join('')}</div><button class="ghost" data-leave-room>Leave Room</button></div>`}
function battle(){if(!state)return home();if(!state.isHatched)return `<section class="page feature-page"><button class="ghost" data-nav="hub">← Battle / Train</button><h1>LAN Battle</h1><div class="battle-message"><strong>Battle unlocks after hatching.</strong><br>Care for the egg for 24 hours and complete at least three care actions.</div><button class="btn" data-nav="journal">Open Journal</button></section>`;if(PokeState.isInDaycare(state))return `<section class="page feature-page"><button class="ghost" data-nav="hub">← Battle / Train</button><h1>LAN Battle</h1><div class="battle-message"><strong>Your Pokémon is at Daycare.</strong><br>It returns in <span id="daycare-timer">${duration(state.daycareUntil-Date.now())}</span> and cannot battle while training.</div><button class="btn" data-nav="train">View Daycare</button></section>`;if(battleTarget)return `<section class="page battle-page battle-active">${battleArena(battleTarget)}</section>`;return `<section class="page feature-page battle-page"><button class="ghost" data-nav="home">← Habitat</button><h1>LAN Battle</h1>${roomRole?roomView():`<p>Host a room or find rooms on the same Wi‑Fi.</p><div class="feature-row"><button class="btn" data-host>Host Room</button><button class="btn" data-discover>Find Rooms</button></div>${battleMessage?`<div class="battle-message">${battleMessage}</div>`:''}<div class="move-list">${peers.map((p,i)=>`<div class="move-card"><strong>${p.name}’s Room</strong><span>${p.species} · Lv.${p.level}</span><button data-join-room="${i}">Join Room</button></div>`).join('')}</div>`}</section>`}
function render(page=location.hash.slice(1)||'home'){if(state?.alive){state=PokeState.advance(state);save()}if(page==='directory'&&state?.alive)page='home';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));view.innerHTML=({home,directory,journal,about,hub,train,battle}[page]||home)();bind()}
function bind(){
  clearTimeout(battleReturnTimer);if(battleTarget&&battleResult){const turnCount=battleResult.turns?.length||1;battleReturnTimer=setTimeout(()=>{if(battleStep<turnCount)battleStep++;else if(battleResult.finished){battleTarget=null;battleResult=null;battleState=null;battleStep=-1}else{battleState={myHp:battleResult.finalHp.challenger,enemyHp:battleResult.finalHp.defender,round:battleResult.round+1};battleResult=null;battleStep=-1}render('battle')},battleStep<turnCount?1400:battleResult.finished?1800:900)}
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=e=>{e.preventDefault();location.hash=b.dataset.nav;render(b.dataset.nav)});
  document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{state=PokeState.act(state,b.dataset.action);save();render('home')});
  document.querySelector('[data-evolve]')?.addEventListener('click',()=>{state=PokeState.evolve(state);save();render('home')});
  document.querySelector('[data-restart]')?.addEventListener('click',()=>{if(confirm('Begin a new lifecycle? Your journal will be cleared.')){state=null;save();location.hash='directory';render('directory')}});
  document.querySelectorAll('[data-pokemon]').forEach(c=>c.onclick=()=>{if(state?.alive)return;const p=POKE_CATALOG.find(x=>x.id===+c.dataset.pokemon);if(!p)return;state=PokeState.newPet(p.id,p.name,Date.now(),p.forms,{learnsets:BATTLE_DATA.learnsetsFor(p.forms),learnset:BATTLE_DATA.learnsetFor(p.type,p.id),evolutionRules:p.evolutionRules});save();location.hash='home';render('home')});
  document.querySelectorAll('[data-relearn]').forEach(b=>b.onclick=()=>{state=PokeState.learnMove(state,b.dataset.relearn,+b.dataset.slot);save();render('train')});
  document.querySelector('[data-daycare]')?.addEventListener('click',()=>{state=PokeState.sendToDaycare(state);save();render('train')});
  document.querySelector('[data-host]')?.addEventListener('click',async()=>{try{roomData=await window.lanBattle.host(battleProfile());roomRole='host';battleMessage='';render('battle')}catch(e){battleMessage=e.message;render('battle')}});
  document.querySelector('[data-discover]')?.addEventListener('click',async()=>{battleMessage='Searching for rooms…';render('battle');const ownId=battleProfile().id;peers=(await window.lanBattle?.discover()||[]).filter(peer=>peer.id!==ownId);battleMessage=peers.length?`Choose one of ${peers.length} room(s).`:'No other rooms found yet.';render('battle')});
  document.querySelectorAll('[data-join-room]').forEach(b=>b.onclick=async()=>{roomPeer=peers[+b.dataset.joinRoom];battleMessage='Joining room…';render('battle');try{roomData=await window.lanBattle.join(roomPeer,battleProfile());roomRole='guest';battleMessage='';render('battle')}catch(e){roomRole='';battleMessage=e.message;render('battle')}});
  document.querySelector('[data-refresh-room]')?.addEventListener('click',async()=>{try{roomData=roomRole==='host'?await window.lanBattle.host(battleProfile()):await window.lanBattle.roomStatus(roomPeer);render('battle')}catch(e){battleMessage=e.message;render('battle')}});
  document.querySelectorAll('[data-enter-battle]').forEach(b=>b.onclick=()=>{battleTarget=b.dataset.enterBattle==='host'?{...roomData.profile,address:roomPeer.address,port:roomPeer.port}:roomData.members[+b.dataset.enterBattle];battleResult=null;battleState={myHp:100,enemyHp:100,round:1};battlePending=false;battleStep=-1;render('battle')});
  document.querySelectorAll('[data-battle-move]').forEach(b=>b.onclick=async()=>{if(battlePending)return;const move=BATTLE_DATA.moves[b.dataset.battleMove],target=battleTarget;battlePending=true;render('battle');try{const response=await window.lanBattle.challenge(target,{...battleProfile(),move,battleState:{challengerHp:battleState.myHp,defenderHp:battleState.enemyHp,round:battleState.round}});if(battleTarget!==target)return;battleResult=response;battlePending=false;battleStep=0;if(battleResult.finished){state=PokeState.awardBattle(state,battleResult);save()}render('battle')}catch(e){if(battleTarget!==target)return;battlePending=false;battleMessage=e.message;battleTarget=null;battleState=null;battleStep=-1;render('battle')}});
  document.querySelector('[data-exit-battle]')?.addEventListener('click',()=>{battleTarget=null;battleResult=null;battleState=null;battlePending=false;battleStep=-1;render('battle')});
  document.querySelector('[data-leave-room]')?.addEventListener('click',()=>{roomRole='';roomPeer=null;roomData=null;battleTarget=null;battleResult=null;battleState=null;battlePending=false;battleStep=-1;render('battle')});
  const s=document.querySelector('#search');if(s)s.oninput=()=>{query=s.value;render('directory')};const t=document.querySelector('#type');if(t)t.onchange=()=>{type=t.value;render('directory')}
}
document.querySelector('[data-window="minimize"]')?.addEventListener('click',()=>window.desktopWindow?.minimize());
document.querySelector('[data-window="close"]')?.addEventListener('click',()=>window.desktopWindow?.close());
document.querySelector('[data-window="pin"]')?.addEventListener('click',async e=>{const pinned=await window.desktopWindow?.togglePin();e.currentTarget.classList.toggle('unpinned',!pinned);e.currentTarget.title=pinned?'Always on top':'Normal window'});
setInterval(()=>{document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const timer=document.querySelector('#daycare-timer');if(timer&&state?.daycareUntil){timer.textContent=duration(state.daycareUntil-Date.now());if(Date.now()>=state.daycareUntil){state=PokeState.advance(state);save();render(location.hash.slice(1)||'home')}}},1000);addEventListener('hashchange',()=>render());render();
