const view=document.querySelector('#view');const KEY='poketamagachi.save.v1';let state=load();let query='';let type='all';let peers=[];let battleMessage='';
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(!saved)return null;const entry=POKE_CATALOG.find(p=>p.id===saved.id);if(!entry){localStorage.removeItem(KEY);return null}saved.forms=entry.forms;saved.evolutionRules=entry.evolutionRules;saved.formIndex=saved.formIndex||0;if(typeof saved.isHatched!=='boolean'){saved.isHatched=true;saved.hatchedAt=saved.bornAt}saved.carePoints=saved.carePoints||0;saved.level=saved.level||1;saved.exp=saved.exp||0;saved.learnset=saved.learnset||BATTLE_DATA.learnsetFor(entry.type);saved.moves=saved.moves||['tackle'];saved.moveArchive=saved.moveArchive||[...saved.moves];saved.pendingMoves=saved.pendingMoves||[];const statNames=['hp','attack','defense','spAttack','spDefense','speed'];saved.ivs=saved.ivs||Object.fromEntries(statNames.map(s=>[s,0]));saved.evs=saved.evs||Object.fromEntries(statNames.map(s=>[s,0]));return saved}catch{return null}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function petDef(){return POKE_CATALOG.find(p=>p.id===state?.id)}function img(p,cls=''){return `<img class="${cls}" src="${p.sprite}" onerror="if(this.src!=='${p.fallback}')this.src='${p.fallback}'" alt="${p.name} pixel sprite">`}
function currentForm(p){return p.forms?.[state?.formIndex||0]||p}
function petVisual(form){return state.isHatched?img(form,'pet-sprite evolution-pop'):`<div class="pixel-egg" role="img" aria-label="Mystery Pokémon egg"><i></i></div>`}
function careLabel(action){if(state.isHatched)return action;return{feed:'warm',play:'talk',rest:'rest',clean:'clean',heal:'check'}[action]}
function stat(k,v){return `<div class="stat"><span>${k.toUpperCase()} ${v}</span><div class="track"><div class="fill" style="width:${v}%"></div></div></div>`}
function needsPanel(s){const keys=state.isHatched?['hunger','happiness','energy','hygiene','health']:['happiness','hygiene','health'],cut=Math.ceil(keys.length/2),column=items=>`<div>${items.map(k=>stat(k,s[k])).join('')}</div>`;return `<div class="stats needs-columns">${column(keys.slice(0,cut))}${column(keys.slice(cut))}</div>`}
function expMeter(){const needed=PokeState.expForNext(state.level),percent=Math.min(100,Math.round((state.exp/needed)*100));return `<div class="exp-meter"><div><strong>LV.${state.level}</strong><span>EXP ${state.exp} / ${needed}</span></div><div class="exp-track" role="progressbar" aria-label="Experience toward level ${state.level+1}" aria-valuemin="0" aria-valuemax="${needed}" aria-valuenow="${state.exp}"><i style="width:${percent}%"></i></div></div>`}
function home(){if(!state)return `<section class="page starter-intro"><button class="giant-pokeball" data-nav="directory" aria-label="Choose your starter"><i></i></button><h1>Choose your starter</h1><button class="btn" data-nav="directory">View Pokémon</button></section>`;
  state=PokeState.advance(state);save();const p=petDef(),form=currentForm(p),s=state.stats;const eggText=`CARE ${Math.min(state.carePoints||0,3)}/3 · ${Date.now()-state.bornAt>=86400000?'READY TO HATCH':'KEEP CARING DAILY'}`,careActions=state.isHatched?['feed','play','rest','clean','heal']:['play','clean','heal'];return `<section class="page home-page"><div class="device"><div class="screen ${state.alive?'':'dead'}"><div class="screen-head"><span>${state.isHatched?form.name.toUpperCase():'MYSTERY EGG'}</span><span>${state.isHatched?p.type.toUpperCase():'EGG'}</span></div>${expMeter()}<div class="pet-stage">${petVisual(form)}<div><h2>${state.isHatched?form.name:'MYSTERY EGG'}</h2><p>${state.alive?(state.isHatched?mood(s):eggText):'Your companion has passed on.'}</p></div></div>${needsPanel(s)}</div><div class="actions ${state.isHatched?'':'egg-actions'}">${state.alive?careActions.map(a=>`<button class="action" data-action="${a}"><span>${careLabel(a)}</span></button>`).join(''):`<button class="action" data-restart><span>restart</span></button>`}</div></div><div class="feature-row"><button class="btn secondary" data-nav="journal">Journal</button><button class="btn" data-nav="hub">Battle / Train</button></div></section>`}
function mood(s){const low=Object.entries(s).filter(([,v])=>v<30).sort((a,b)=>a[1]-b[1])[0];if(!low)return 'Everything feels just right!';return {hunger:'My tummy is rumbling…',happiness:'Can we play for a while?',energy:'I need a little nap.',hygiene:'My habitat needs cleaning.',health:'I do not feel very well…'}[low[0]]}
function directory(){if(state?.alive)return home();const list=POKE_CATALOG.filter(p=>(type==='all'||p.type===type)&&p.name.toLowerCase().includes(query.toLowerCase()));const types=[...new Set(POKE_CATALOG.map(p=>p.type))];return `<section class="page"><div class="directory-head"><div><div class="eyebrow">Companion directory · ${POKE_CATALOG.length} available</div><h1>Choose your starter</h1></div><p>Every starter begins as an egg.</p></div><div class="filters"><input id="search" value="${query}" placeholder="Search by name…"><select id="type"><option value="all">All types</option>${types.map(t=>`<option ${t===type?'selected':''}>${t}</option>`).join('')}</select></div><div class="grid">${list.map(p=>`<article class="card" data-pokemon="${p.id}">${img(p)}<span class="type">#${String(p.id).padStart(3,'0')} · ${p.type}</span><h3>${p.name}</h3><button class="choose-card" type="button">Choose</button></article>`).join('')}</div></section>`}
function journal(){if(!state)return `<section class="page"><button class="ghost" data-nav="home">← Back</button><div class="empty"><h1>No memories yet.</h1><p>Choose a companion to begin your journal.</p><button class="btn" data-nav="directory">Browse directory</button></div></section>`;return `<section class="page"><button class="ghost" data-nav="home">← Habitat</button><div class="eyebrow">Shared memories</div><h1>Journal</h1><div class="journal">${state.journal.map(e=>`<div class="journal-item"><time>${new Date(e.at).toLocaleString()}</time><strong>${e.text}</strong></div>`).join('')}</div></section>`}
function about(){return `<section class="page"><div class="empty"><div class="eyebrow">Care guide</div><h1>A little care goes a long way.</h1><p>Needs decay based on real elapsed time—even when the app is closed. Feed, play, rest, clean, and heal your companion. Neglected critical needs lower health; zero health ends the lifecycle and unlocks a fresh start.</p><button class="btn" data-nav="directory">Meet the roster</button></div></section>`}
function moveName(id){return BATTLE_DATA.moves[id]?.name||id}function hub(){if(!state)return home();const waiting=state.isHatched?'Find players on this Wi‑Fi':'Opens after your egg hatches';return `<section class="page feature-page"><button class="ghost" data-nav="home">← Habitat</button><h1>Battle / Train</h1><div class="hub-grid"><button class="hub-card" data-nav="battle"><strong>Battle</strong><span>${waiting}</span></button><button class="hub-card" data-nav="train"><strong>Train</strong><span>Level, EXP, stats and moves</span></button></div></section>`}
function nextEvolution(){const rule=state.evolutionRules?.[state.formIndex];if(!rule)return'Final evolution';return rule.type==='level'?`Level ${rule.value}`:rule.type==='random'?`Random Eevee evolution at level ${rule.value}`:rule.type==='item'?`Use ${rule.value}`:rule.type==='trade'?'Trade with another player':rule.type==='friendship-day'?'High friendship during daytime':'High friendship'}
function train(){if(!state)return home();const available=state.moveArchive.filter(m=>!state.moves.includes(m)),labels={hp:'HP',attack:'ATK',defense:'DEF',spAttack:'SP.ATK',spDefense:'SP.DEF',speed:'SPEED'};return `<section class="page feature-page"><button class="ghost" data-nav="hub">← Battle / Train</button><h1>Train</h1>${expMeter()}${state.isHatched?`<div class="battle-message">NEXT: ${nextEvolution()}</div>`:'<div class="battle-message">Your Pokémon is still inside the egg. Care for it until it hatches; training and moves will then unlock.</div>'}<h2>IVs / EVs</h2><div class="stat-grid">${Object.keys(labels).map(k=>`<div><span>${labels[k]}</span><strong>IV ${state.ivs[k]}</strong><strong>EV ${state.evs[k]}</strong></div>`).join('')}</div>${state.isHatched?`<h2>Moves (${state.moves.length}/4)</h2><div class="move-list">${state.moves.map(m=>`<div class="move-card"><strong>${moveName(m)}</strong><span>${BATTLE_DATA.moves[m]?.type||'normal'} · ${BATTLE_DATA.moves[m]?.power||'status'} power</span></div>`).join('')}</div><h2>Move Relearner</h2>${available.length?available.map(m=>`<div class="move-card"><strong>${moveName(m)}</strong><div class="replace-row">${state.moves.map((x,i)=>`<button data-relearn="${m}" data-slot="${i}">Replace ${moveName(x)}</button>`).join('')}</div></div>`).join(''):'<p>No forgotten moves.</p>'}`:''}</section>`}
function battleProfile(){const form=currentForm(petDef());return{name:state.name,species:form.name,level:state.level,moves:state.moves,formId:form.id}}
function battle(){if(!state)return home();if(!state.isHatched)return `<section class="page feature-page"><button class="ghost" data-nav="hub">← Battle / Train</button><h1>LAN Battle</h1><div class="battle-message"><strong>Battle unlocks after hatching.</strong><br>Care for the egg for 24 hours and complete at least three care actions.</div><button class="btn" data-nav="journal">Open Journal</button></section>`;return `<section class="page feature-page"><button class="ghost" data-nav="home">← Habitat</button><h1>LAN Battle</h1><p>Both players must be on the same Wi‑Fi and have this page open.</p><div class="feature-row"><button class="btn" data-host>Host</button><button class="btn" data-discover>Find players</button></div>${battleMessage?`<div class="battle-message">${battleMessage}</div>`:''}<div class="move-list">${peers.map((p,i)=>`<div class="move-card"><strong>${p.name} · ${p.species} Lv.${p.level}</strong>${state.moves.map(m=>`<button data-challenge="${i}" data-move="${m}">Use ${moveName(m)}</button>`).join('')}</div>`).join('')}</div></section>`}
function render(page=location.hash.slice(1)||'home'){if(page==='directory'&&state?.alive)page='home';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));view.innerHTML=({home,directory,journal,about,hub,train,battle}[page]||home)();bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=e=>{e.preventDefault();location.hash=b.dataset.nav;render(b.dataset.nav)});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{state=PokeState.act(state,b.dataset.action);save();render('home')});document.querySelector('[data-restart]')?.addEventListener('click',()=>{if(confirm('Begin a new lifecycle? Your journal will be cleared.')){state=null;save();location.hash='directory';render('directory')}});document.querySelectorAll('[data-pokemon]').forEach(c=>c.onclick=()=>{if(state?.alive)return;const p=POKE_CATALOG.find(x=>x.id===+c.dataset.pokemon);if(!p)return;state=PokeState.newPet(p.id,p.name,Date.now(),p.forms,{learnset:BATTLE_DATA.learnsetFor(p.type),evolutionRules:p.evolutionRules});save();location.hash='home';render('home')});document.querySelectorAll('[data-relearn]').forEach(b=>b.onclick=()=>{state=PokeState.learnMove(state,b.dataset.relearn,+b.dataset.slot);save();render('train')});document.querySelectorAll('[data-use-item]').forEach(b=>b.onclick=()=>{state=PokeState.useItem(state,b.dataset.useItem);save();render('train')});document.querySelector('[data-host]')?.addEventListener('click',async()=>{await window.lanBattle?.host(battleProfile());battleMessage='Hosting on this Wi‑Fi…';render('battle')});document.querySelector('[data-discover]')?.addEventListener('click',async()=>{battleMessage='Searching…';render('battle');peers=await window.lanBattle?.discover()||[];battleMessage=peers.length?`Choose one of ${peers.length} player(s).`:'No players found yet.';render('battle')});document.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=async()=>{const peer=peers[+b.dataset.challenge],move=BATTLE_DATA.moves[b.dataset.move];battleMessage=`Battling ${peer.name}…`;render('battle');try{const result=await window.lanBattle.challenge(peer,{...battleProfile(),move});state=PokeState.awardBattle(state,result);save();battleMessage=`${result.won?'Victory':'Defeat'} vs ${peer.name}! +${result.exp} EXP${result.item?` · Found ${result.item}`:''}`;render('battle')}catch(e){battleMessage=e.message;render('battle')}});const s=document.querySelector('#search');if(s)s.oninput=()=>{query=s.value;render('directory')};const t=document.querySelector('#type');if(t)t.onchange=()=>{type=t.value;render('directory')}}
document.querySelector('[data-window="minimize"]')?.addEventListener('click',()=>window.desktopWindow?.minimize());
document.querySelector('[data-window="close"]')?.addEventListener('click',()=>window.desktopWindow?.close());
document.querySelector('[data-window="pin"]')?.addEventListener('click',async e=>{const pinned=await window.desktopWindow?.togglePin();e.currentTarget.classList.toggle('unpinned',!pinned);e.currentTarget.title=pinned?'Always on top':'Normal window'});
setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),1000);addEventListener('hashchange',()=>render());render();
