const view=document.querySelector('#view');const KEY='poketamagachi.save.v1';let state=load();let query='';let type='all';
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function petDef(){return POKE_CATALOG.find(p=>p.id===state?.id)}function img(p,cls=''){return `<img class="${cls}" src="${p.sprite}" onerror="if(this.src!=='${p.fallback}')this.src='${p.fallback}'" alt="${p.name} pixel sprite">`}
function ballIcon(kind){const colors={poke:['#ef5350','#f8f2e4'],great:['#4c83c3','#ef5350'],ultra:['#222426','#f4c542'],premier:['#f5f1e8','#ef5350'],master:['#8d5cab','#ef7caf'],moon:['#263451','#f4dc62'],berry:['#ef5350','#74a94d']}[kind]||['#ef5350','#f8f2e4'];return `<span class="item-icon ${kind}" style="--ball-a:${colors[0]};--ball-b:${colors[1]}" aria-hidden="true"><i></i></span>`}
function actionIcon(action){return{feed:ballIcon('berry'),play:ballIcon('great'),rest:ballIcon('moon'),clean:ballIcon('premier'),heal:ballIcon('master')}[action]}
function stat(k,v){return `<div class="stat"><span>${k.toUpperCase()} ${v}</span><div class="track"><div class="fill" style="width:${v}%"></div></div></div>`}
function home(){if(!state)return `<section class="page hero"><div><div class="eyebrow">Your tiny world is waiting</div><h1>Choose a pal.<br><em>Care every day.</em></h1><p>A cozy desktop companion inspired by classic virtual-pet toys. Your chosen Pokémon stays with you through every snack, nap, and adventure.</p><div class="hero-actions"><button class="btn" data-nav="directory">Choose your companion →</button><button class="btn secondary" data-nav="about">How it works</button></div></div><img class="key-art" src="assets/pocket-pal-key-art.png" alt="Pixel art virtual-pet device"></section>`;
  state=PokeState.advance(state);save();const p=petDef(),s=state.stats;return `<section class="page"><div class="device"><div class="screen ${state.alive?'':'dead'}"><div class="screen-head"><span>DAY ${Math.max(1,Math.ceil((Date.now()-state.bornAt)/86400000))} · ${state.stage.toUpperCase()}</span><span>${p.type.toUpperCase()}</span></div><div class="pet-stage">${img(p)}<div><h2>${state.name||p.name}</h2><p>${state.alive?mood(s):'Your companion has passed on.'}</p></div></div><div class="stats">${Object.entries(s).map(([k,v])=>stat(k,v)).join('')}</div></div><div class="actions">${state.alive?['feed','play','rest','clean','heal'].map(a=>`<button class="action" data-action="${a}">${actionIcon(a)}<span>${a}</span></button>`).join(''):`<button class="action" data-restart>${ballIcon('poke')}<span>restart</span></button>`}</div></div></section>`}
function mood(s){const low=Object.entries(s).filter(([,v])=>v<30).sort((a,b)=>a[1]-b[1])[0];if(!low)return 'Everything feels just right!';return {hunger:'My tummy is rumbling…',happiness:'Can we play for a while?',energy:'I need a little nap.',hygiene:'My habitat needs cleaning.',health:'I do not feel very well…'}[low[0]]}
function directory(){const list=POKE_CATALOG.filter(p=>(type==='all'||p.type===type)&&p.name.toLowerCase().includes(query.toLowerCase()));const types=[...new Set(POKE_CATALOG.map(p=>p.type))];return `<section class="page"><div class="directory-head"><div><div class="eyebrow">Companion directory · ${POKE_CATALOG.length} available</div><h1>Find your forever pal.</h1></div><p>${state?'A companion is already chosen. Restart after its lifecycle ends to choose again.':'This choice stays with you for its whole lifecycle.'}</p></div><div class="filters"><input id="search" value="${query}" placeholder="Search by name…"><select id="type"><option value="all">All types</option>${types.map(t=>`<option ${t===type?'selected':''}>${t}</option>`).join('')}</select></div><div class="grid">${list.map(p=>`<article class="card ${state?'locked':''}" data-pokemon="${p.id}">${img(p)}<span class="type">#${String(p.id).padStart(3,'0')} · ${p.type}</span><h3>${p.name}</h3><span class="type">${p.nature} nature</span></article>`).join('')}</div></section>`}
function journal(){if(!state)return `<section class="page"><div class="empty"><h1>No memories yet.</h1><p>Choose a companion to begin your journal.</p><button class="btn" data-nav="directory">Browse directory</button></div></section>`;return `<section class="page"><div class="eyebrow">Shared memories</div><h1>Journal</h1><div class="journal">${state.journal.map(e=>`<div class="journal-item"><time>${new Date(e.at).toLocaleString()}</time><strong>${e.text}</strong></div>`).join('')}</div></section>`}
function about(){return `<section class="page"><div class="empty"><div class="eyebrow">Care guide</div><h1>A little care goes a long way.</h1><p>Needs decay based on real elapsed time—even when the app is closed. Feed, play, rest, clean, and heal your companion. Neglected critical needs lower health; zero health ends the lifecycle and unlocks a fresh start.</p><button class="btn" data-nav="directory">Meet the roster</button></div></section>`}
function render(page=location.hash.slice(1)||'home'){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));view.innerHTML=({home:home,directory,journal,about}[page]||home)();bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=e=>{e.preventDefault();location.hash=b.dataset.nav;render(b.dataset.nav)});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{state=PokeState.act(state,b.dataset.action);save();render('home')});document.querySelector('[data-restart]')?.addEventListener('click',()=>{if(confirm('Begin a new lifecycle? Your journal will be cleared.')){state=null;save();render('directory')}});document.querySelectorAll('[data-pokemon]').forEach(c=>c.onclick=()=>{if(state)return;const p=POKE_CATALOG.find(x=>x.id===+c.dataset.pokemon);const name=prompt(`Name your ${p.name}:`,p.name);if(name!==null){state=PokeState.newPet(p.id,name.trim()||p.name);save();location.hash='home';render('home')}});const s=document.querySelector('#search');if(s)s.oninput=()=>{query=s.value;render('directory')};const t=document.querySelector('#type');if(t)t.onchange=()=>{type=t.value;render('directory')}}
document.querySelector('[data-window="minimize"]')?.addEventListener('click',()=>window.desktopWindow?.minimize());
document.querySelector('[data-window="close"]')?.addEventListener('click',()=>window.desktopWindow?.close());
document.querySelector('[data-window="pin"]')?.addEventListener('click',async e=>{const pinned=await window.desktopWindow?.togglePin();e.currentTarget.classList.toggle('unpinned',!pinned);e.currentTarget.title=pinned?'Always on top':'Normal window'});
setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),1000);addEventListener('hashchange',()=>render());render();
