(function(root){
  const MAX=100, HOUR=3600000, DAY=86400000, DAYCARE_DURATION=2*HOUR, SHINY_CHANCE=1/100;
  const clamp=n=>Math.max(0,Math.min(MAX,Math.round(n*100)/100));
  const dayKey=now=>{const date=new Date(now);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
  const previousDayKey=now=>{const date=new Date(now);date.setDate(date.getDate()-1);return dayKey(date)};
  function newPet(id,name,now=Date.now(),forms=[],profile={}){const learnsets=profile.learnsets||{},learnset=learnsets[forms?.[0]?.id]||profile.learnset||[],startingAll=[...new Set(learnset.filter(x=>x.level<=1).map(x=>x.move))],starting=startingAll.slice(-4),stats=['hp','attack','defense','spAttack','spDefense','speed'],ivs={},evs={},shinyRoll=profile.shinyRoll??Math.random(),isShiny=profile.isShiny??shinyRoll<SHINY_CHANCE;for(const stat of stats){ivs[stat]=Math.floor(Math.random()*32);evs[stat]=0}return{id,name:name||forms?.[0]?.name||'',hasNickname:Boolean(profile.hasNickname),isShiny,bornAt:now,hatchedAt:null,lastUpdated:now,lastAction:now,stage:'Egg',isHatched:false,carePoints:0,formIndex:0,forms,evolutionRules:profile.evolutionRules||[],level:1,exp:0,learnsets,learnset,moves:starting,moveArchive:startingAll,pendingMoves:[],daycareUntil:null,careExpDay:null,careExpActions:[],healthyStreak:0,lastHealthyDay:null,pokedex:{species:[],shiny:[],opponents:[]},ivs,evs,items:[],trades:0,wins:0,losses:0,alive:true,stats:{hunger:88,happiness:82,energy:76,hygiene:90,health:100},journal:[{at:now,text:profile.hasNickname?`${name}'s mysterious egg arrived. Care for it every day!`:'A mysterious egg arrived. Care for it every day!'}]};}
  function ensurePokedex(p){p.pokedex=p.pokedex||{species:[],shiny:[],opponents:[]};p.pokedex.species=p.pokedex.species||[];p.pokedex.shiny=p.pokedex.shiny||[];p.pokedex.opponents=p.pokedex.opponents||[];return p.pokedex}
  function syncPokedex(p){const dex=ensurePokedex(p);if(!p.isHatched)return p;const index=p.formIndex||0,branched=p.evolutionRules?.[0]?.type==='random',ownedForms=branched&&index>0?[p.forms?.[0],p.forms?.[index]]:(p.forms||[]).slice(0,index+1);for(const form of ownedForms.filter(Boolean)){let entry=dex.species.find(item=>item.id===form.id);if(entry)entry.owned=true;else dex.species.push({id:form.id,name:form.name,owned:true});if(p.isShiny){entry=dex.shiny.find(item=>item.id===form.id);if(entry)entry.owned=true;else dex.shiny.push({id:form.id,name:form.name,owned:true})}}return p}
  function updateGrowth(p,now){
    if(!p.isHatched&&now-p.bornAt>=DAY&&(p.carePoints||0)>=3){p.isHatched=true;p.hatchedAt=now;p.stage='Hatchling';const species=p.forms?.[0]?.name||p.name;p.journal.unshift({at:now,text:p.isShiny?`The egg hatched into ${species} — it is shiny!`:`The egg hatched into ${species}!`});}
    if(!p.isHatched){p.stage='Egg';return p;}
    p.stage=p.level>=36?'Veteran':p.level>=16?'Growing':'Hatchling';return syncPokedex(p);
  }
  const expForNext=level=>level*50;
  function syncFormLearnset(p){const formId=p.forms?.[p.formIndex||0]?.id,next=p.learnsets?.[formId];if(!next)return p;p.learnset=next;for(const lesson of next){if(lesson.level<=p.level&&!p.moveArchive.includes(lesson.move)){p.moveArchive.push(lesson.move);if(p.moves.length<4)p.moves.push(lesson.move);else p.pendingMoves.push(lesson.move)}}return p}
  function evolutionReady(p){if(!p?.isHatched||!p.alive)return false;const rule=p.evolutionRules?.[p.formIndex||0];if(!rule)return false;if(rule.type==='level'||rule.type==='random')return p.level>=rule.value;if(rule.type==='friendship')return p.stats.happiness>=90;if(rule.type==='friendship-day'){const hour=new Date().getHours();return p.stats.happiness>=90&&hour>=6&&hour<18}if(rule.type==='trade')return(p.trades||0)>0;if(rule.type==='item')return(p.items||[]).includes(rule.value);return false}
  function checkEvolution(p){p.canEvolve=evolutionReady(p);return p}
  function evolve(pet,rng=Math.random){const p=JSON.parse(JSON.stringify(pet));if(!evolutionReady(p))return checkEvolution(p);const current=p.formIndex||0,rule=p.evolutionRules[current],desired=rule.type==='random'?1+Math.floor(rng()*Math.max(1,p.forms.length-1)):current+1;if(rule.type==='item'){const index=p.items.indexOf(rule.value);if(index>=0)p.items.splice(index,1)}const before=p.forms[current]?.name||p.name,after=p.forms[desired]?.name||p.name;p.formIndex=desired;if(!p.hasNickname)p.name=after;syncFormLearnset(p);p.journal.unshift({at:Date.now(),text:p.hasNickname?`${p.name} evolved from ${before} into ${after}!`:`${before} evolved into ${after}!`});return checkEvolution(syncPokedex(p))}
  function gainExp(pet,amount,rng=Math.random){const p=JSON.parse(JSON.stringify(pet));if(!p.isHatched||!p.alive)return p;p.exp=(p.exp||0)+Math.max(0,amount);while(p.level<100&&p.exp>=expForNext(p.level)){p.exp-=expForNext(p.level);p.level++;p.journal.unshift({at:Date.now(),text:`Reached level ${p.level}!`});for(const lesson of p.learnset||[]){if(lesson.level===p.level&&!p.moveArchive.includes(lesson.move)){p.moveArchive.push(lesson.move);if(p.moves.length<4)p.moves.push(lesson.move);else p.pendingMoves.push(lesson.move);}}}checkEvolution(p,rng);return p;}
  function learnMove(pet,move,replaceIndex=null){const p=JSON.parse(JSON.stringify(pet));if(!p.moveArchive.includes(move))return p;if(p.moves.includes(move))return p;if(p.moves.length<4)p.moves.push(move);else if(Number.isInteger(replaceIndex)&&replaceIndex>=0&&replaceIndex<4)p.moves[replaceIndex]=move;return p;}
  function awardBattle(pet,result){let p=gainExp(advance(pet),result.exp||0);const stat=result.won?'attack':'defense',battleDamage=Math.max(0,100-(result.finalHp?.challenger??(result.won?100:0))),healthCost=Math.ceil(battleDamage*.25);p.evs[stat]=Math.min(252,(p.evs[stat]||0)+(result.won?2:1));p[result.won?'wins':'losses']=(p[result.won?'wins':'losses']||0)+1;p.stats.hunger=clamp(p.stats.hunger-6);p.stats.energy=clamp(p.stats.energy-10);p.stats.hygiene=clamp(p.stats.hygiene-4);p.stats.happiness=clamp(p.stats.happiness+(result.won?4:-5));p.stats.health=clamp(p.stats.health-healthCost);if(result.won&&p.stats.health===0)p.stats.health=1;p.journal.unshift({at:Date.now(),text:`${result.won?'Won':'Completed'} a LAN battle, took ${battleDamage} battle damage, and earned ${result.exp||0} EXP.`});if(result.item&&!p.items.includes(result.item))p.items.push(result.item);return p;}
  function useItem(pet,item){const p=JSON.parse(JSON.stringify(pet));if(!p.items.includes(item))return p;return checkEvolution(p)}
  function recordOpponent(pet,profile,now=Date.now()){const p=JSON.parse(JSON.stringify(pet)),dex=ensurePokedex(p),species={id:profile.formId||null,name:profile.actualSpecies||profile.species||profile.name||'Unknown'},same=entry=>species.id?entry.id===species.id:entry.name===species.name;if(!dex.species.some(same))dex.species.push(species);if(profile.isShiny&&!dex.shiny.some(same))dex.shiny.push(species);const key=profile.id||`${profile.name||'Trainer'}-${species.name}`,existing=dex.opponents.find(entry=>entry.key===key);if(existing){existing.encounters=(existing.encounters||1)+1;existing.level=profile.level||existing.level;existing.lastSeen=now;existing.isShiny=existing.isShiny||Boolean(profile.isShiny)}else dex.opponents.unshift({key,trainer:profile.name||'Trainer',species:species.name,level:profile.level||1,isShiny:Boolean(profile.isShiny),encounters:1,lastSeen:now});return p}
  const isInDaycare=(pet,now=Date.now())=>Boolean(pet?.daycareUntil&&pet.daycareUntil>now);
  function sendToDaycare(pet,now=Date.now()){const p=advance(pet,now);if(!p?.alive||!p.isHatched||isInDaycare(p,now))return p;p.daycareStartedAt=now;p.daycareUntil=now+DAYCARE_DURATION;p.journal.unshift({at:now,text:'Went to Daycare for a two-hour training session.'});return p}
  function advance(pet,now=Date.now()){
    if(!pet||!pet.alive)return pet;
    const hours=Math.max(0,(now-pet.lastUpdated)/HOUR);let p=JSON.parse(JSON.stringify(pet)),s=p.stats;
    if(hours){if(p.isHatched){s.hunger=clamp(s.hunger-hours*5);s.energy=clamp(s.energy-hours*4)}s.happiness=clamp(s.happiness-hours*3);s.hygiene=clamp(s.hygiene-hours*3);const watched=p.isHatched?[s.hunger,s.happiness,s.energy,s.hygiene]:[s.happiness,s.hygiene],healthDrain=watched.reduce((total,value)=>total+(value<=0?12:value<15?5:0),0);s.health=clamp(s.health-hours*healthDrain+(healthDrain===0&&s.health<100?hours:0.5*hours));}
    updateGrowth(p,now);
    if(p.isHatched&&p.daycareUntil&&now>=p.daycareUntil){const reward=100+p.level*10;p.daycareUntil=null;p.daycareStartedAt=null;p=gainExp(p,reward);p.journal.unshift({at:now,text:`Returned from Daycare and earned ${reward} EXP!`});s=p.stats;}
    p.lastUpdated=now;if(s.health<=0){p.alive=false;p.journal.unshift({at:now,text:`${p.name||'Your companion'} passed on. Your memories remain.`});}return p;
  }
  const effects={feed:{hunger:28,happiness:3,energy:-2},play:{happiness:24,energy:-12,hunger:-6,hygiene:-4},rest:{energy:36,health:5,hunger:-8},clean:{hygiene:40,happiness:3},heal:{health:30,energy:8,happiness:-3}};
  function act(pet,action,now=Date.now()){
    const p=advance(pet,now);if(!p?.alive||!effects[action])return p;const out=JSON.parse(JSON.stringify(p));
    const eggNeeds=new Set(['happiness','hygiene','health']);for(const [key,value] of Object.entries(effects[action]))if(out.isHatched||eggNeeds.has(key))out.stats[key]=clamp(out.stats[key]+value);
    if(!out.isHatched)out.carePoints=(out.carePoints||0)+1;updateGrowth(out,now);
    const labels={feed:'Shared a tasty berry.',play:'Played a lively little game.',rest:'Curled up for a good rest.',clean:'Freshened up the habitat.',heal:'Took some medicine.'};
    out.lastAction=now;out.journal.unshift({at:now,text:labels[action]});if(out.isHatched&&!isInDaycare(out,now)){const today=dayKey(now);if(out.careExpDay!==today){out.careExpDay=today;out.careExpActions=[]}if(!out.careExpActions.includes(action)){out.careExpActions.push(action);Object.assign(out,gainExp(out,2));out.journal.unshift({at:now,text:`First ${action} care today: +2 EXP.`})}const healthy=['hunger','happiness','energy','hygiene','health'].every(key=>out.stats[key]>=60);if(out.careExpActions.length===5&&healthy&&out.lastHealthyDay!==today){out.healthyStreak=out.lastHealthyDay===previousDayKey(now)?Math.min((out.healthyStreak||0)+1,7):1;out.lastHealthyDay=today;const reward=out.healthyStreak*20;Object.assign(out,gainExp(out,reward));out.journal.unshift({at:now,text:`Healthy care streak day ${out.healthyStreak}: +${reward} EXP!`})}}out.journal=out.journal.slice(0,30);return out;
  }
  const api={newPet,advance,act,clamp,gainExp,learnMove,expForNext,checkEvolution,evolutionReady,evolve,awardBattle,useItem,recordOpponent,syncPokedex,isInDaycare,sendToDaycare,DAYCARE_DURATION,SHINY_CHANCE};root.PokeState=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
